### ISSUE TITLE
mahony_simpletest.py function calls to mahony() computeAngles()

### ISSUE THREAD

**Issue by somenice** [gamblor21/CircuitPython_AHRS#3]
It seemed I had to update a couple lines to run mahony_simpletest.py 
Line 37 - m = mahony.Mahony() (required upper case function name)
Line 79 - m.compute_angles() (vs computeAngles())

Thanks for sharing

**Comment by gamblor21** [comment]
Thanks, I ignored the example and forgot to update it.
