### ISSUE TITLE
Ambiguous instructions for gyro calibration

### ISSUE THREAD

**Issue by ehippy** [gamblor21/CircuitPython_AHRS#5]
The wiki states one should "Note the average gx/gy/gz values". Which one: "Uncalibrated gyro" or "Gyro"?

Reading the code it appears the Gyro value is what I should use as it's being averaged.

```
Uncalibrated gyro:  (0.0126754, 0.02474, -0.0195477)
Gyro:  (0.0143024, 0.0275528, -0.0213714)
```
I'd submit a PR, but I don't have access to write to the wiki.

Thanks for putting this together, I'm getting promising results!

**Comment by gamblor21** [comment]
Thanks for catching this. I clarified it in the wiki. Glad it is giving you promising results!
